name: Deploy to Firebase on Push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm ci
        working-directory: ./functions

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOURDONE_LENDING_GLEB82 }}'
          
          # --- ВОТ ВАЖНАЯ СТРОКА, КОТОРАЯ ВСЁ ИСПРАВИТ ---
          channelId: live
          
          projectId: tourdone-lending-gleb82
